### ISSUE TITLE
Backups PROD

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/tumeplay-back#2]
Mettre en place les backups de la BDD PG vers Azure Blob.

Option pour @Wonsy  : possibilité d'utiliser un serveur dédié [Azure Postgres](https://azure.microsoft.com/fr-fr/services/postgresql/) plutôt que de l'inclure dans le docker-compose

**Comment by revolunet** [comment]
Résolu?

**Comment by Wonsy** [comment]
Au temps pour moi : résolu depuis plusieurs semaines oui; clôture de l'issue.
